[package]
name = "cw-asset"
description = "Helper library for interacting with Cosmos assets (SDK coins and CW20 tokens)"
version = "1.0.2"
authors = ["larry <larry@delphidigital.io>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/mars-protocol/cw-asset"

[features]
# `legacy` feature implements methods that cast `Asset` instances to/from legacy asset classes that
# some projects may use 
legacy = ["astroport"]

[dependencies]
cosmwasm-std = "^0.16"
cw20 = "^0.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

astroport = { version = "^1.0", optional = true }