[package]
name        = "cw-asset"
description = "Helper library for interacting with Cosmos assets (native coins, CW20, and CW1155 tokens)"
version     = "2.4.0"
authors     = ["larry <larry@delphidigital.io>"]
edition     = "2021"
license     = "GPL-3.0-or-later"
repository  = "https://github.com/mars-protocol/cw-asset"

[dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std    = "1.1"
cw20            = "0.16"
cw1155          = "0.16"
cw-storage-plus = "0.16"

[dev-dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
