[package]
name = "cw-asset"
description = "Helper library for interacting with Cosmos assets (SDK coins and CW20 tokens)"
version = "1.0.3-beta" # beta because `mars-core` is still at the "rc" version
authors = ["larry <larry@delphidigital.io>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/mars-protocol/cw-asset"

[features]
# `asroport` and `mars` features implements methods that cast `cw-asset` classes to/from legacy 
# classes used by the corresponding projects
#
# NOTE: `astroport` feature is automatically created by the optional dependency that goes by the 
# same name, so no need to define again here
mars = ["mars-core"]

[dependencies]
# mandatory dependencies
cosmwasm-std = "^0.16"
cw20 = "^0.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

# optional dependencies
astroport = { version = "^1.0", optional = true }
mars-core = { git = "https://github.com/mars-protocol/mars-core", tag = "v1.0.0-rc4", optional = true }